# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: auth
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value: {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MF_AUTH_DB
              value: {{ .Values.postgresqlauth.auth.database | quote }}
            - name: MF_AUTH_DB_HOST
            {{- if .Values.postgresqlauth.enabled }}
              value: {{ .Release.Name }}-postgresqlauth
            {{- else }}
              value: {{ .Values.postgresqlauth.postgresqlHost | quote }}
            {{- end }}
            - name: MF_AUTH_DB_PASS
              value: {{ .Values.postgresqlauth.auth.postgresPassword | quote }}
            - name: MF_AUTH_DB_PORT
              value: "{{ .Values.auth.dbPort }}"
            - name: MF_AUTH_DB_USER
              value: {{ .Values.postgresqlauth.auth.username | quote }}
            - name: MF_AUTH_GRPC_PORT
              value: "{{ .Values.auth.grpcPort }}"
            - name: MF_AUTH_HTTP_PORT
              value: "{{ .Values.auth.httpPort }}"
            - name: MF_AUTH_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.auth.logLevel }}
            - name: MF_AUTH_SECRET
              value: "{{ .Values.auth.secret }}"
            - name: MF_USERS_ADMIN_EMAIL
              value: "{{ .Values.users.adminEmail }}"
            - name: MF_USERS_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.users.grpcPort }}
            - name: MF_THINGS_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.things.authGrpcPort }}
          image: "{{ default .Values.defaults.image.repository .Values.auth.image.repository }}/auth:{{ default .Values.defaults.image.tag .Values.auth.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.users.image.pullPolicy }}
          name: {{ .Release.Name }}-auth
          ports:
            - containerPort: {{ .Values.auth.httpPort }}
              protocol: TCP
            - containerPort: {{ .Values.auth.grpcPort }}
              protocol: TCP
      {{- if .Values.defaults.image.pullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.defaults.image.pullSecret }}"
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
