# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-influxdb-writer-config
data:
  config.toml: |
    # To listen all messsage broker subjects use default value "channels.>".
    # To subscribe to specific subjects use values starting by "channels." and
    # followed by a subtopic (e.g ["channels.<channel_id>.sub.topic.x", ...]).
    [subscriber]
    subjects = ["channels.>"]
    [transformer]
    # SenML or JSON
    format = "senml"
    # Used if format is SenML
    content_type = "application/senml+json"
    # Used as timestamp fields if format is JSON
    time_fields = [{ field_name = "seconds_key", field_format = "unix",    location = "UTC"},
                   { field_name = "millis_key",  field_format = "unix_ms", location = "UTC"},
                   { field_name = "micros_key",  field_format = "unix_us", location = "UTC"},
                   { field_name = "nanos_key",   field_format = "unix_ns", location = "UTC"}]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-influxdb-writer
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: influxdb-writer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: influxdb-writer
    spec:
      containers:
        - env:
            - name: MF_INFLUX_WRITER_LOG_LEVEL
              value: debug
            - name: MF_BROKER_URL
              value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
            - name: MF_INFLUX_WRITER_PORT
              value: "{{ .Values.influxdb.writer.httpPort }}"
            - name: MF_INFLUX_WRITER_BATCH_SIZE
              value: "5000"
            - name: MF_INFLUX_WRITER_BATCH_TIMEOUT
              value: "5"
            - name: MF_INFLUXDB_DB
              value: "{{ .Values.influxdb.database }}"
            - name: MF_INFLUXDB_BUCKET
              value: "{{ .Values.influxdb.auth.admin.bucket }}"
            - name: MF_INFLUXDB_ORG
              value: "{{ .Values.influxdb.auth.admin.org }}"
            - name: MF_INFLUXDB_TOKEN
              value: "{{ .Values.influxdb.auth.admin.token }}"
            - name: MF_INFLUXDB_ADMIN_USER
              value: "{{ .Values.influxdb.auth.admin.username }}"
            - name: MF_INFLUXDB_ADMIN_PASSWORD
              value: "{{ .Values.influxdb.auth.admin.password }}"
            - name: MF_INFLUXDB_HOST
              value: {{ .Release.Name }}-influxdb
            - name: MF_INFLUXDB_PORT
              value: "{{ .Values.influxdb.dbPort }}"
            - name: MF_INFLUX_WRITER_CONFIG_PATH
              value: "{{ .Values.influxdb.configPath }}"
          image: "{{ default .Values.defaults.image.repository .Values.influxdb.writer.image.repository }}/influxdb-writer:{{ default .Values.defaults.image.tag .Values.influxdb.writer.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.influxdb.writer.image.pullPolicy }}
          name: {{ .Release.Name }}-influxdb-writer
          ports:
            - containerPort: {{ .Values.influxdb.writer.httpPort }}
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: {{ .Values.influxdb.configPath }}
              name: influxdb-writer-config
              subPath: config.toml
      {{- if .Values.defaults.image.pullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.defaults.image.pullSecret }}"
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-influxdb-writer-config
            optional: false
          name: influxdb-writer-config
{{- end }}
