# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.notifier_smtp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifier-smtp
spec:
  selector:
    app: {{ .Release.Name }}
    component: notifier-smtp
{{- end }}
